### ISSUE TITLE
Clears models bound value on the input 

### ISSUE THREAD

**Issue by house9** [pzuraq/ember-inputmask#1]
When changing my input field from 'input' to 'phone-number-input' it clears my bound field value, see below:

mobile using 'phone-number-input' with bound value is cleared
![image](https://cloud.githubusercontent.com/assets/52154/5786978/07e985f2-9da4-11e4-9911-bca32f817540.png)

standard input is fine
![image](https://cloud.githubusercontent.com/assets/52154/5786983/201b7e78-9da4-11e4-8c4d-cc5817970553.png)

any ideas?

**Comment by pzuraq** [comment]
@house9 Hey, can you post the code so I can take a look? Also, are you binding to unmaskedValue or value?

**Comment by pzuraq** [comment]
So it turns out that `value` was being erased no matter what, I tracked it down and fixed it. Thank you for bringing that to my attention!

You probably still want to bind to unmaskedValue, unless you want to store the phone number *with* formatting.

**Comment by house9** [comment]
Thanks - I can confirm that `value` now works properly.

But, I did switch to `unmaskedValue` per your suggestion, I do clean up the phone server side - however sticking with unmasked is definitely better
