### ISSUE TITLE
Amex credid card mask is wrong!

### ISSUE THREAD

**Issue by fatihakkoyun** [pzuraq/ember-inputmask#11]
in credit-card-input.js American Express card mask must be '9999-999999-99999' instead of '9999-9999999-99999'.
Written one number more.

**Comment by pzuraq** [comment]
Hey! Sorry about this, could you make a PR to fid that change? I'm no longer actively working on this addon, but I'll continue to merge PRs for the forseeable future.

**Comment by AO16** [comment]
https://github.com/pzuraq/ember-inputmask/pull/13

**Comment by leizhao4** [comment]
I assume this is taken care of by #20. Let us know if I'm wrong and we can reopen this.
