### ISSUE TITLE
ENOENT error with ember-inputmask and jquery.inputmask

### ISSUE THREAD

**Issue by ErunamoJAZZ** [pzuraq/ember-inputmask#15]
Hello.

I had this error trying to use ember-inputmask 0.2.x with jquery.inputmask 3.2.5:
´ENOENT: no such file or directory, stat '~/App/tmp/concat_with_maps-input_base_path-vZJDIM25.tmp/0/bower_components/jquery.inputmask/dist/jquery.inputmask.bundle.min.js'´

But ember-inputmask 2.0.0 works with jquery.inputmask 3.1.49

**Comment by leizhao4** [comment]
Thank you @ErunamoJAZZ! This should be fixed in #29. The file path changed between the two versions of jquery.inputmask.
