### ISSUE TITLE
missing universal-phone-input.js under the addon folder

### ISSUE THREAD

**Issue by saparatus** [pzuraq/ember-inputmask#2]
ember-cli newbie here, sorry in advance if this is not an issue.

After running `ember g ember-input-mask`, `ember serve` complains about `universal-phone-input` missing. Error goes away after deleting `node_modules//ember-inputmask/app/components/universal-phone-input.js` which tries to import the said component.

**Comment by pzuraq** [comment]
Ah yes, that got left in by mistake. The universal phone mask was supposed to use the phone mask extension from jquery.inputmask, but I cut it due to performance issues (would quite literally freeze my browser).

Thank you for bringing this up!
