### ISSUE TITLE
Usage with ember-test-selectors

### ISSUE THREAD

**Issue by KillaPL** [pzuraq/ember-inputmask#42]
Hey

I would like to use `input-mask` with ember-test-selectors, simply to be able to set `data-test-selector` property on input. Can I do that easily with ember-inputmask? And if not, how would I go about extending ember-inputmask to allow for that?

**Comment by brandynbennett** [comment]
You should be able to just drop the attributes right on the component
```
{{number-input group=true
  placeholder='0.00'
  data-test-my-test-selector=true
  decimal=true
  unmaskedValue=myAmount}}

```

**Comment by KillaPL** [comment]
@brandynbennett For various reasons, we moved to approach like this:

```
<div data-test-selector={{testSelector}}>
  {{one-way-input-mask}}
</div>
```

So I would consider the issue solved. Sorry for stalling this for so long.
